title: AdvancedGUI
description: Official wiki for AdvancedGUI
remote_theme: "pmarsceill/just-the-docs"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

logo: "/assets/logo.png"

aux_links:
  "Web Editor":
    - "https://advancedgui.app/"
  "Java Docs":
    - "https://advancedgui.app/apidocs/"
  "Discord":
    - "https://discord.gg/ycDG6rS"

aux_links_new_tab: true
